### ISSUE TITLE
Error with module

### ISSUE THREAD

**Issue by maggick** [digininja/pipal#7]
I try to use some module and I get an error :

pipal-modular/checkers_available/FR_area_codes.rb:145:in `get_results': undefined method `length' for nil:NilClass (NoMethodError)
        from ./pipal.rb:717:in `block (2 levels) in <main>'
        from ./pipal.rb:716:in `each'
        from ./pipal.rb:716:in `block in <main>'
        from /usr/lib/ruby/1.9.1/benchmark.rb:280:in `measure'
        from ./pipal.rb:75:in `<main>'

I do not have this error with the FR_color_checker module !

**Comment by maggick** [comment]
just locked at my open issues and see this one. No more problem.
